// const data = [
//     {
//         id: 1,
//         fecha_tmk: '2022-08-10',
//         IDENTIFICADOR: '123123',
//         id_table: '10',
//         IDEFECTO: '20',
//         IDMOTIVO: '5',
//         IDCONTACTO: '4',
//         OBSERVACION: 'ninguna',
//         IDTELEFONO: '12',
//         IDDIRECCION: '13',
//         IDPERSONAL: '14',
//         NOMCONTACTO: 'prueba',
//         PISOS: 'pisos',
//         PUERTA: 'puerta',
//         FACHADA: 'fachada',
//         fecha_asignacion: '2010-05-10',
//         fecha_analisis: '2012-08-15',
//         estado : 'activo',
//         id_registro : '18',
//         fecha_promesa: '2014-10-20',
//         monto_promesa: '50',
//         fecha_programacion: '2017-08-14'
//     },
//     {
//         id: 2,
//         fecha_tmk: '2022-08-10',
//         IDENTIFICADOR: '123123',
//         id_table: '10',
//         IDEFECTO: '20',
//         IDMOTIVO: '5',
//         IDCONTACTO: '4',
//         OBSERVACION: 'ninguna',
//         IDTELEFONO: '12',
//         IDDIRECCION: '13',
//         IDPERSONAL: '14',
//         NOMCONTACTO: 'prueba',
//         PISOS: 'pisos',
//         PUERTA: 'puerta',
//         FACHADA: 'fachada',
//         fecha_asignacion: '2010-05-10',
//         fecha_analisis: '2012-08-15',
//         estado : 'activo',
//         id_registro : '18',
//         fecha_promesa: '2014-10-20',
//         monto_promesa: '50',
//         fecha_programacion: '2017-08-14'
//     },
//     {
//         id: 3,
//         fecha_tmk: '2022-08-10',
//         IDENTIFICADOR: '123123',
//         id_table: '10',
//         IDEFECTO: '20',
//         IDMOTIVO: '5',
//         IDCONTACTO: '4',
//         OBSERVACION: 'ninguna',
//         IDTELEFONO: '12',
//         IDDIRECCION: '13',
//         IDPERSONAL: '14',
//         NOMCONTACTO: 'prueba',
//         PISOS: 'pisos',
//         PUERTA: 'puerta',
//         FACHADA: 'fachada',
//         fecha_asignacion: '2010-05-10',
//         fecha_analisis: '2012-08-15',
//         estado : 'activo',
//         id_registro : '18',
//         fecha_promesa: '2014-10-20',
//         monto_promesa: '50',
//         fecha_programacion: '2017-08-14'
//     },
//     {
//         id: 4,
//         fecha_tmk: '2022-08-10',
//         IDENTIFICADOR: '123123',
//         id_table: '10',
//         IDEFECTO: '20',
//         IDMOTIVO: '5',
//         IDCONTACTO: '4',
//         OBSERVACION: 'ninguna',
//         IDTELEFONO: '12',
//         IDDIRECCION: '13',
//         IDPERSONAL: '14',
//         NOMCONTACTO: 'prueba',
//         PISOS: 'pisos',
//         PUERTA: 'puerta',
//         FACHADA: 'fachada',
//         fecha_asignacion: '2010-05-10',
//         fecha_analisis: '2012-08-15',
//         estado : 'activo',
//         id_registro : '18',
//         fecha_promesa: '2014-10-20',
//         monto_promesa: '50',
//         fecha_programacion: '2017-08-14'
//     },
//     {
//         id: 5,
//         fecha_tmk: '2022-08-10',
//         IDENTIFICADOR: '123123',
//         id_table: '10',
//         IDEFECTO: '20',
//         IDMOTIVO: '5',
//         IDCONTACTO: '4',
//         OBSERVACION: 'ninguna',
//         IDTELEFONO: '12',
//         IDDIRECCION: '13',
//         IDPERSONAL: '14',
//         NOMCONTACTO: 'prueba',
//         PISOS: 'pisos',
//         PUERTA: 'puerta',
//         FACHADA: 'fachada',
//         fecha_asignacion: '2010-05-10',
//         fecha_analisis: '2012-08-15',
//         estado : 'activo',
//         id_registro : '18',
//         fecha_promesa: '2014-10-20',
//         monto_promesa: '50',
//         fecha_programacion: '2017-08-14'
//     },
//     {
//         id: 6,
//         fecha_tmk: '2022-08-10',
//         IDENTIFICADOR: '123123',
//         id_table: '10',
//         IDEFECTO: '20',
//         IDMOTIVO: '5',
//         IDCONTACTO: '4',
//         OBSERVACION: 'ninguna',
//         IDTELEFONO: '12',
//         IDDIRECCION: '13',
//         IDPERSONAL: '14',
//         NOMCONTACTO: 'prueba',
//         PISOS: 'pisos',
//         PUERTA: 'puerta',
//         FACHADA: 'fachada',
//         fecha_asignacion: '2010-05-10',
//         fecha_analisis: '2012-08-15',
//         estado : 'activo',
//         id_registro : '18',
//         fecha_promesa: '2014-10-20',
//         monto_promesa: '50',
//         fecha_programacion: '2017-08-14'
//     },
// ]